"""
compare_gcs_gps.py
------------------
Compares which globular clusters each catalog (LVDB and Vasiliev & Baumgardt 2021)
identifies as falling within the Roman GPS main footprint, matching entries
between the two catalogs by RA/Dec proximity.

Generated by Claude, corrected by Robyn Sanderson 6 Mar 2026
"""

import numpy as np
from astropy import units as u
from astropy.coordinates import SkyCoord

from roman_nearfield import read_gcs, select_gcs_in_gps_main, get_sky_coords

# ── Load both catalogs and select GPS clusters ────────────────────────────────

gcs_lvdb = read_gcs(vb=False)
gcs_vb   = read_gcs(vb=True)

idx_lvdb = select_gcs_in_gps_main(gcs_lvdb)
idx_vb   = select_gcs_in_gps_main(gcs_vb)

# Subset to GPS clusters only
gps_lvdb = gcs_lvdb[idx_lvdb]
gps_vb   = gcs_vb[idx_vb]

coords_lvdb = get_sky_coords(gps_lvdb)
coords_vb   = get_sky_coords(gps_vb)

print(f"LVDB:  {len(gps_lvdb)} clusters in GPS")
print(f"V&B:   {len(gps_vb)}  clusters in GPS")

# ── Cross-match by position (tolerance = 1 arcsec) ───────────────────────────

MATCH_TOL = 0.01 * u.deg

idx_vb_match, sep, _ = coords_lvdb.match_to_catalog_sky(coords_vb)
matched = sep < MATCH_TOL

# ── Report ────────────────────────────────────────────────────────────────────

print(f"\n{matched.sum()} clusters matched between catalogs (within {MATCH_TOL}):")
print(f"{'Name (LVDB)':<30} {'RA (LVDB)':>12} {'Dec (LVDB)':>12} "
      f"{'Name (V&B)':<30} {'RA (V&B)':>12} {'Dec (V&B)':>12} {'Sep (\")':>8}")
print("-" * 110)
for i, (m, j) in enumerate(zip(matched, idx_vb_match)):
    if m:
        print(f"{gps_lvdb['name'][i]:<30} "
              f"{gps_lvdb['ra'][i]:>12.5f} {gps_lvdb['dec'][i]:>12.5f} "
              f"{gps_vb['name'][j]:<30} "
              f"{gps_vb['ra'][j]:>12.5f} {gps_vb['dec'][j]:>12.5f} "
              f"{sep[i].to(u.arcsec).value:>8.3f}")

# ── Clusters in LVDB but not matched in V&B ──────────────────────────────────

lvdb_only = gps_lvdb[~matched]
if len(lvdb_only) > 0:
    print(f"\n{len(lvdb_only)} cluster(s) in LVDB GPS selection but not matched in V&B:")
    for row in lvdb_only:
        print(f"  {row['name']:<30}  ra={row['ra']:.5f}  dec={row['dec']:.5f}")
else:
    print("\nAll LVDB GPS clusters matched in V&B.")

# ── Clusters in V&B but not matched in LVDB ──────────────────────────────────

# Find V&B entries that were not the nearest match to any LVDB entry
matched_vb_indices = set(idx_vb_match[matched])
vb_only_mask = np.array([i not in matched_vb_indices for i in range(len(gps_vb))])
vb_only = gps_vb[vb_only_mask]

if len(vb_only) > 0:
    print(f"\n{len(vb_only)} cluster(s) in V&B GPS selection but not matched in LVDB:")
    for row in vb_only:
        print(f"  {row['name']:<30}  ra={row['ra']:.5f}  dec={row['dec']:.5f}")
else:
    print("\nAll V&B GPS clusters matched in LVDB.")
